apiVersion: v2
description: The mdsntk site helm chart
keywords:
  - site
maintainers:
  - email: admin@mdsn.tk
    name: Nicky Lemeshko
name: site
appVersion: "0.1.0"
version: 0.1.0
dependencies:
  - name: ecommerce-platform
    repository: file://../../mdsntk-platform
    version: 0.1.0
    alias: site