deployment:
  enabled: true
  name: site
  namespace: mdsntk
  replicas: 2
  appName: mdsntk
  role: api
  containerName: site-container
  imageRepository: ghcr.io/nlemeshko/mdsntk
  imageTag: "0.1.5"
  port: 80
service:
  enabled: true
  name: site-service
  namespace: mdsntk
  appName: mdsntk
  type: ClusterIP
  servicePort: 80
  targetPort: 80
serviceAccount:
  enabled: true
  name: site-service-account
  namespace: mdsntk
namespace:
  enabled: true
ingress:
  enabled: false