# Deployment object
deployment:
  enabled: true
  name: site
  namespace: mdsntk
  replicas: 3
  appName: site
  role: nginx
  containerName: site-container
  imageRepository: ghcr.io/nlemeshko/mdsntk
  imageTag: "1.4.1"
  port: 80
# Service object
service:
  enabled: true
  name: site-service
  namespace: mdsntk
  appName: site
  type: ClusterIP
  servicePort: 80
  targetPort: 80
# Service Account object
serviceAccount:
  enabled: true
  name: site-service-account
  namespace: mdsntk
# Namespace object
namespace:
  enabled: enable
  name: mdsntk
# Ingress 
ingress:
  enabled: true
  name: site-ingress
  path: /
  host: mdsn.demo.gns-it.dev
