global:
  chartName: site
site:
  # Deployment object
  deployment:
    enabled: true
    name: site
    namespace: mdsntk
    replicas: 2
    appName: site
    role: api
    containerName: site-container
    imageRepository: ghcr.io/nlemeshko/mdsntk
    imageTag: "0.1.4"
    port: 80
  # Service object
  service:
    enabled: true
    name: site-service
    namespace: mdsntk
    appName: site
    type: ClusterIP
    servicePort: 80
    targetPort: 80
  # Service Account object
  serviceAccount:
    enabled: true
    name: site-service-account
    namespace: mdsntk
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false