apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
data:
  default.conf: |
    server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location ~ \.php$ {
        root           html;
        fastcgi_pass   php-{{ .Values.deployment.containerName }}:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        include        fastcgi_params;
    }
    }
